### ISSUE TITLE
List of schemas on map aggregator should include `solidarity_economy_initiatives-v0.1.0`

### ISSUE THREAD

**Issue by wu-lee** [MurmurationsNetwork/MurmurationsServices#153]
I notice the list of schemas hasn't changed now that the `solidarity_economy_initiatives-v0.1.0` schema has been added to the MurmurationsLibrary.

https://aggregator.murmurations.network/

Does something need to be done manually when new schemas are added?

**Comment by geoffturk** [comment]
MPG was expecting an integer instead of a string for the `metadata.schema.version`. I [switched it to an integer](https://github.com/MurmurationsNetwork/MurmurationsLibrary/pull/39/files) for now so it appears in MPG, but will switch it back to a semver string once MPG is updated to parse semver strings for versioning.
